# Generated by Django 4.1.7 on 2023-03-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecode',
            name='coming_stock',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='storecode',
            name='stock',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
